# Generated by Django 6.0.6 on 2026-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=20)),
                ('parcel_type', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=15)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=15)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('booking_date', models.DateTimeField()),
                ('current_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'e-commerce',
            },
        ),
    ]
